COMPILER=javac

ArrayMaximalAdjacentDifference:
	$(COMPILER) ArrayMaximalAdjacentDifference.java 

run:
	java ArrayMaximalAdjacentDifference < input.txt

clean:
	rm ArrayMaximalAdjacentDifference.class